# Generated by Django 4.2.3 on 2024-01-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Bookings', models.CharField(max_length=50)),
                ('customer_order_number', models.CharField(max_length=50)),
                ('builty_number', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('booking_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('drivers_name', models.CharField(max_length=100)),
                ('drivers_id', models.CharField(max_length=50)),
                ('drivers_mobile', models.CharField(max_length=15)),
                ('pending_at_company', models.BooleanField(default=True)),
                ('products_bank_payment_slip_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_of_the_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('zafar_and_brothers_bank_account_number', models.CharField(max_length=50)),
                ('target_bank_account', models.CharField(max_length=50)),
                ('warehouse_booking', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_picture', models.ImageField(blank=True, null=True, upload_to='media')),
                ('status', models.CharField(max_length=50)),
                ('tons', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordered_total_bags', models.IntegerField()),
            ],
        ),
    ]
