# Generated by Django 4.2.3 on 2024-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybooking',
            old_name='products_bank_payment_slip_number',
            new_name='bank_payment_slip_number',
        ),
        migrations.AddField(
            model_name='companybooking',
            name='product',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
