# Generated by Django 4.2.3 on 2024-01-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_companybooking_pending_at_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybooking',
            name='booking_price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
