# Generated by Django 4.2.3 on 2024-01-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_companybooking_booking_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_name', models.CharField(max_length=255)),
                ('system_generated_bilty_number', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('drivers_name', models.CharField(max_length=255)),
                ('drivers_id', models.CharField(max_length=20)),
                ('stock_location', models.CharField(max_length=255)),
                ('delivered_status', models.CharField(max_length=20)),
                ('drivers_mobile', models.CharField(max_length=15)),
                ('tons', models.DecimalField(decimal_places=2, max_digits=25)),
                ('ordered_bags', models.IntegerField()),
                ('pending_ordered_bags', models.IntegerField()),
                ('delivered_bags', models.IntegerField()),
                ('dispatched', models.BooleanField()),
                ('product', models.CharField(max_length=255)),
                ('bank_payment_slip_number', models.FileField(upload_to='media')),
                ('payment_type', models.CharField(max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_expected_date', models.DateField()),
                ('bank_name', models.CharField(max_length=255)),
                ('zafar_and_brothers_account_number', models.CharField(max_length=255)),
                ('target_trader_account', models.CharField(max_length=255)),
                ('warehouse_booking', models.BooleanField()),
                ('fare_paid_by', models.CharField(max_length=20)),
                ('invoice_picture', models.ImageField(upload_to='media')),
                ('freight_paid', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
