# Generated by Django 4.2.3 on 2024-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='warehouse_booking',
            field=models.CharField(max_length=255),
        ),
    ]
