# Generated by Django 4.2.3 on 2024-01-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_deal_warehouse_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='trader_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
