# Generated by Django 4.2.3 on 2024-01-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_deal_system_generated_bilty_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='delivered_bags',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
