# Generated by Django 4.2.3 on 2024-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_deal_fare_paid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('system_generated_bilty_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deal_freight', models.CharField(max_length=20)),
                ('third_party_name', models.CharField(max_length=255)),
                ('thrid_party_paid_fare', models.CharField(max_length=255)),
                ('paid_by_self', models.CharField(max_length=255)),
                ('owner_transport_fare', models.CharField(max_length=255)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('drivers_name', models.CharField(max_length=255)),
                ('drivers_id', models.CharField(max_length=20)),
                ('stock_location', models.CharField(max_length=255)),
                ('delivered_status', models.CharField(max_length=20)),
                ('drivers_mobile', models.CharField(max_length=15)),
                ('tons', models.DecimalField(decimal_places=2, max_digits=25)),
                ('ordered_total_bags', models.IntegerField()),
                ('pending_ordered_bags_at_traders_area', models.IntegerField()),
                ('delivered_bags', models.IntegerField(blank=True, null=True)),
                ('dispatched', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('bank_payment_slip_number', models.FileField(upload_to='media')),
                ('payment_type', models.CharField(max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_expected_date', models.DateField()),
                ('bank_name', models.CharField(max_length=255)),
                ('zafar_and_brothers_account_number', models.CharField(max_length=255)),
                ('target_trader_account', models.CharField(max_length=255)),
                ('warehouse_booking', models.CharField(max_length=255)),
                ('fare_paid_by', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_picture', models.ImageField(upload_to='media')),
                ('freight_paid', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
