# Generated by Django 4.2.3 on 2024-03-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_module3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(max_length=255)),
                ('stock_in', models.CharField(max_length=122)),
                ('stock_out', models.CharField(max_length=122)),
                ('per_bag_price', models.CharField(max_length=122)),
                ('total_tons', models.DecimalField(decimal_places=2, max_digits=25)),
                ('number_of_bags', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('stock_out_price', models.CharField(max_length=122)),
                ('remaining_stock_price', models.CharField(max_length=122)),
                ('profit', models.CharField(max_length=122)),
            ],
        ),
    ]
